[LIP-3] incorporate feedbacks
libra/lip pull request #91
Opened 2020-12-01 01:29 UTC by zekun000

2020-12-01 02:29 UTC, aching requested changes
Looks pretty good, a few nits.

2020-12-01 02:29 UTC, aching commented on lips/lip-3.md
> +Libra Upgrade Management (LUM) is a set of protocols to reconfigure the blockchain. With respect to time-sensitive decisions and incident response, LUM provides the Libra Networks--a subsidiary of th
Does the -- render nicely and intentional?

2020-12-01 02:29 UTC, aching commented on lips/lip-3.md
> +The goal of LUM is to provide the means to effectively remediate any plausible operational incident in a transparent manner.
LUM is both for normal upgrades as well as quickly resolve incidents right?

```suggestion
The goal of LUM is to provide the means to effectively and transparently update the software in order to meet changing requirements as well as remediate any plausible operational incident.
```

2020-12-01 02:29 UTC, aching commented on lips/lip-3.md
> +All building blocks may be used for "business-as-usual" upgrades or as urgent measures.
```suggestion
All building blocks may be used for "business-as-usual" upgrades or to address urgent measures.
```

2020-12-01 02:29 UTC, aching commented on lips/lip-3.md
> +To release a new version of software LN needs to coordinate the release plan and timeline with all the validator operators. Validator operators are responsible for deploying the software release as p
```suggestion
In order to release a new version of software, LN needs to coordinate the release plan and timeline with all the validator operators. Validator operators are responsible for deploying the software release as per the provided instructions.
```

2020-12-01 02:29 UTC, aching commented on lips/lip-3.md
> +On-chain state can only be updated via transactions. We propose three ways to execute critical updates, ordered by most frequently to least frequently: normal multi-sig transactions, multi-sig WriteS
```suggestion
On-chain state can only be updated via transactions. We propose three ways to execute critical updates, ordered by most frequent to least frequent: normal multi-sig transactions, multi-sig WriteSet transactions, and genesis transactions.
```

2020-12-01 02:29 UTC, aching commented on lips/lip-3.md
> +Normal transactions go through VM and invoke Libra Framework modules (see LIP-2) to produce a Writeset that alters ledger state. Both the resulting state change and the authenticating set of signatur
Maybe add the link to LIP-2?

```suggestion
Normal transactions go through the VM and invoke Libra Framework modules (see LIP-2) to produce a Writeset that alters ledger state. Both the resulting state change and the authenticating set of signatures are transparent and visible on-chain for auditing.
```

2020-12-01 02:29 UTC, aching commented on lips/lip-3.md
> +There are two types of upgrades in the system - (i) updates to the Libra protocol software and (ii) changes to on-chain state. We discuss them correspondingly.
Maybe consider making i and ii links to the other sections?

2020-12-01 02:29 UTC, aching commented on lips/lip-3.md
> +It should be noted that the Association appoints Libra Network(LN) officers. Officers are accountable for their actions, and usual measures may be taken upon deviation from their expected conduct.  H
I personally feel like this sentence is not important for this LIP and can be removed.

2020-12-01 03:04 UTC, aching approved these changes

2020-12-01 03:04 UTC, aching commented on lips/lip-3.md
> +In order to release a new version of software, Libra Network (LN) needs to coordinate the release plan and timeline with all the validator operators. Validator operators are responsible for deploying
```suggestion
In order to release a new version of software, Libra Networks (LN) needs to coordinate the release plan and timeline with all the validator operators. Validator operators are responsible for deploying the software release as per the provided instructions.
```

2020-12-01 05:35 UTC, merged

2020-12-03 01:47 UTC, dahliamalkhi reviewed
@zekun000 please see stylistic comments

2020-12-03 01:47 UTC, dahliamalkhi commented on lips/lip-3.md
>  We first present all building blocks and the reasoning, followed by concrete examples.
I would delete this sentence

2020-12-03 01:47 UTC, dahliamalkhi commented on lips/lip-3.md
>  Specification changes go through the LIP process and non-specification changes (e.g. bug fixes and performance improvements) do not need to initiate the LIP process. All software changes are submitte
1. pls add ref to LIP-0 
2. initiate the LIP process --> go through it

2020-12-03 01:47 UTC, dahliamalkhi commented on lips/lip-3.md
> +Some changes may require all validators to transition at the same height, which is accompanied with an [on-chain state update](#on-chain-state-upgrade).
height -> chain height (or blockchain height)
accompanied with --> implemented by

2020-12-03 01:47 UTC, dahliamalkhi commented on lips/lip-3.md
> +On-chain state can only be updated via transactions. We propose three ways to execute critical updates, ordered by most frequent to least frequent: normal multi-sig transactions, multi-sig WriteSet t
why "critical updates"? these could either be "business as usual" or urgent. How about:

.....three ways [to effectuate changes to the LPN by directly mutating on-chain state].

2020-12-03 01:47 UTC, dahliamalkhi commented on lips/lip-3.md
> +There are two types of upgrades in the system - (i) [updates to the Libra protocol software](#software-upgrade) and (ii) [changes to on-chain state](#on-chain-state-upgrade). We discuss them correspo
I propose the following start:


Conceptually, the software running on validator nodes comprises two layers. One is a *blockchain core* whose goal is to replicate a ledger of transactions and their outcome. The second is a *framework* that stores the ledger-state and a set of software modules  -- encoded in the Move programming language -- that define the rules for interacting with the LPN and mutating the ledge-state (see also LIP-2[ref]). There are two corresponding type of upgrades to the system, (i) updates to the core software (ii) updates to the framework state

2020-12-03 01:47 UTC, dahliamalkhi commented on lips/lip-3.md
> +Normal transactions go through the VM and invoke Libra Framework modules (see [LIP-2](./lip-2.md)) to produce a Writeset that alters ledger state. Both the resulting state change and the authenticati
alters <the> ledger-state.

2020-12-03 01:47 UTC, dahliamalkhi commented on lips/lip-3.md
> +Writeset transactions are a special type of multi-sig transactions that prescribes an arbitrary state change. Unlike normal transactions, which must follow rules such as “the reserve is the only enti
"than generate one using the blockchain logic that is encoded in Move" --> than go through the Framework modules/rules.

2020-12-03 01:47 UTC, dahliamalkhi commented on lips/lip-3.md
>  Even though WriteSet transactions can describe arbitrary state change, they are authenticated with the same multi-sig mechanism as normal transactions which means both the change and multi-sig are tr
can describe --> prescribe

2020-12-03 01:47 UTC, dahliamalkhi commented on lips/lip-3.md
> +Genesis transactions can be either normal or WriteSet transactions. As the name suggests, the process is similar to how the very first genesis transaction works. The genesis transaction applies on to
"the process.." of generating a genesis transaction?

2020-12-03 01:47 UTC, dahliamalkhi commented on lips/lip-3.md
>  Note after Libra starts, we may still need genesis transactions as the last resort for extremely unlikely catastrophic scenarios such as losing more than 1/3 validators.
Note -> Note that, (comma)
omit "still"
the last resort -> a last resort
1/3 -> a third

2020-12-03 01:47 UTC, dahliamalkhi commented on lips/lip-3.md
> +The decision flow chart below summarizes the building blocks and how they will be used in specific examples.
omit "in specific examples"